server:
  port: 8089

dubbo:
  application:
    name: webser-web
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
  provider:
    timeout: 1000

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user=admin: admin
    password: admin
    pool:
      enabled: true
      max-connections: 5
      idle-timeout: 30s